public class Exercici6 {
    public static void main(String[] args) {
//        public static void throwException() {
//            throw new NumberNotFoundException("El n√∫mero no s'ha trobat.");
//        }
    }
}
